#!/usr/bin/env python

from lib.OptionsParser import *
from lib.PlummerModel  import *
from lib.DiscModel  import *
from lib.IsoModel  import *
from lib.EtaModel  import *

def plot(plot):
    if plot:
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.hist(eccs,bins=40,cumulative=True,normed=True,alpha=0.5)
        ax.plot(np.arange(0.0,1.0,0.01),np.power(np.arange(0.0,1.0,0.01),2.0))
        ax.plot(np.arange(0.0,1.0,0.01),np.power(np.arange(0.0,1.0,0.01),3.6))
        plt.show()

def main():
    # Parse options
    op = OptionsParser()
    op = op.get_args()

    if op.command == "disc":
        mps = DiscModel(op)
    elif op.command == "iso":
        mps = IsoModel(op)
    elif op.command == "eta":
        mps = EtaModel(op)
    elif op.command == "plummer":
        mps = PlummerModel(op)

    mps.create_model()

    print_model(mps.pos, mps.vel, mps.mass, op.outfile)

if __name__ == "__main__":
    main()


